#############################################################################
# Makefile for building: debug/diary
# Generated by qmake (2.01a) (Qt 4.8.7) on: ?? ??? 11 22:17:26 2016
# Project:  diary.pro
# Template: app
# Command: /usr/lib64/qt4/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile diary.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4 -Imoc
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib64/qt4 -lz -lQtSql -L/usr/lib64/mysql -L/usr/lib64/qt4 -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib64/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = debug/obj/

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		customdelegate.cpp \
		browser.cpp \
		sqlconnectiondialog.cpp \
		treeitem.cpp \
		treemodel.cpp \
		itemselectionmodel.cpp \
		textedit.cpp \
		odt/tools/kzip.cpp \
		odt/tools/docmargin.cpp \
		odt/docformat/ooo/styleparser.cpp \
		odt/docformat/ooo/styleinformation.cpp \
		odt/docformat/ooo/formatproperty.cpp \
		odt/docformat/ooo/document.cpp \
		odt/docformat/ooo/converter.cpp moc/moc_mainwindow.cpp \
		moc/moc_customdelegate.cpp \
		moc/moc_browser.cpp \
		moc/moc_sqlconnectiondialog.cpp \
		moc/moc_treemodel.cpp \
		moc/moc_itemselectionmodel.cpp \
		moc/moc_textedit.cpp \
		moc/moc_docmargin.cpp \
		qrc_textedit.cpp
OBJECTS       = debug/obj/main.o \
		debug/obj/mainwindow.o \
		debug/obj/customdelegate.o \
		debug/obj/browser.o \
		debug/obj/sqlconnectiondialog.o \
		debug/obj/treeitem.o \
		debug/obj/treemodel.o \
		debug/obj/itemselectionmodel.o \
		debug/obj/textedit.o \
		debug/obj/kzip.o \
		debug/obj/docmargin.o \
		debug/obj/styleparser.o \
		debug/obj/styleinformation.o \
		debug/obj/formatproperty.o \
		debug/obj/document.o \
		debug/obj/converter.o \
		debug/obj/moc_mainwindow.o \
		debug/obj/moc_customdelegate.o \
		debug/obj/moc_browser.o \
		debug/obj/moc_sqlconnectiondialog.o \
		debug/obj/moc_treemodel.o \
		debug/obj/moc_itemselectionmodel.o \
		debug/obj/moc_textedit.o \
		debug/obj/moc_docmargin.o \
		debug/obj/qrc_textedit.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		odt/config.pri \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		diary.pro
QMAKE_TARGET  = diary
DESTDIR       = debug/
TARGET        = debug/diary

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) debug/ || $(MKDIR) debug/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9][^0-9]*\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: diary.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		odt/config.pri \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/libQtSql.prl \
		/usr/lib64/qt4/libQtCore.prl \
		/usr/lib64/qt4/libQtXml.prl \
		/usr/lib64/qt4/libQtGui.prl \
		/usr/lib64/qt4/libQtNetwork.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile diary.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
odt/config.pri:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib64/qt4/libQtSql.prl:
/usr/lib64/qt4/libQtCore.prl:
/usr/lib64/qt4/libQtXml.prl:
/usr/lib64/qt4/libQtGui.prl:
/usr/lib64/qt4/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile diary.pro

dist: 
	@$(CHK_DIR_EXISTS) debug/obj/diary1.0.0 || $(MKDIR) debug/obj/diary1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) debug/obj/diary1.0.0/ && $(COPY_FILE) --parents mainwindow.h customdelegate.h browser.h sqlconnectiondialog.h treeitem.h treemodel.h common.h itemselectionmodel.h textedit.h odt/allconfig.h odt/tools/kzip.h odt/tools/docmargin.h odt/docformat/ooo/styleparser.h odt/docformat/ooo/styleinformation.h odt/docformat/ooo/formatproperty.h odt/docformat/ooo/document.h odt/docformat/ooo/converter.h debug/obj/diary1.0.0/ && $(COPY_FILE) --parents textedit.qrc debug/obj/diary1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp customdelegate.cpp browser.cpp sqlconnectiondialog.cpp treeitem.cpp treemodel.cpp itemselectionmodel.cpp textedit.cpp odt/tools/kzip.cpp odt/tools/docmargin.cpp odt/docformat/ooo/styleparser.cpp odt/docformat/ooo/styleinformation.cpp odt/docformat/ooo/formatproperty.cpp odt/docformat/ooo/document.cpp odt/docformat/ooo/converter.cpp debug/obj/diary1.0.0/ && (cd `dirname debug/obj/diary1.0.0` && $(TAR) diary1.0.0.tar diary1.0.0 && $(COMPRESS) diary1.0.0.tar) && $(MOVE) `dirname debug/obj/diary1.0.0`/diary1.0.0.tar.gz . && $(DEL_FILE) -r debug/obj/diary1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc/moc_mainwindow.cpp moc/moc_customdelegate.cpp moc/moc_browser.cpp moc/moc_sqlconnectiondialog.cpp moc/moc_treemodel.cpp moc/moc_itemselectionmodel.cpp moc/moc_textedit.cpp moc/moc_docmargin.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_mainwindow.cpp moc/moc_customdelegate.cpp moc/moc_browser.cpp moc/moc_sqlconnectiondialog.cpp moc/moc_treemodel.cpp moc/moc_itemselectionmodel.cpp moc/moc_textedit.cpp moc/moc_docmargin.cpp
moc/moc_mainwindow.cpp: mainwindow.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc/moc_mainwindow.cpp

moc/moc_customdelegate.cpp: customdelegate.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) customdelegate.h -o moc/moc_customdelegate.cpp

moc/moc_browser.cpp: treemodel.h \
		common.h \
		treeitem.h \
		itemselectionmodel.h \
		browser.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) browser.h -o moc/moc_browser.cpp

moc/moc_sqlconnectiondialog.cpp: sqlconnectiondialog.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) sqlconnectiondialog.h -o moc/moc_sqlconnectiondialog.cpp

moc/moc_treemodel.cpp: common.h \
		treeitem.h \
		treemodel.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) treemodel.h -o moc/moc_treemodel.cpp

moc/moc_itemselectionmodel.cpp: itemselectionmodel.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) itemselectionmodel.h -o moc/moc_itemselectionmodel.cpp

moc/moc_textedit.cpp: odt/allconfig.h \
		odt/docformat/ooo/document.h \
		odt/docformat/ooo/converter.h \
		odt/docformat/ooo/styleparser.h \
		odt/docformat/ooo/formatproperty.h \
		odt/docformat/ooo/styleinformation.h \
		odt/tools/kzip.h \
		odt/tools/docmargin.h \
		textedit.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) textedit.h -o moc/moc_textedit.cpp

moc/moc_docmargin.cpp: odt/tools/docmargin.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) odt/tools/docmargin.h -o moc/moc_docmargin.cpp

compiler_rcc_make_all: qrc_textedit.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_textedit.cpp
qrc_textedit.cpp: textedit.qrc \
		example.html \
		images/logo32.png \
		images/mac/editredo.png \
		images/mac/exportpdf.png \
		images/mac/textright.png \
		images/mac/fileprint.png \
		images/mac/editcopy.png \
		images/mac/textunder.png \
		images/mac/editundo.png \
		images/mac/filesave.png \
		images/mac/editcut.png \
		images/mac/fileopen.png \
		images/mac/textcenter.png \
		images/mac/zoomout.png \
		images/mac/textitalic.png \
		images/mac/filenew.png \
		images/mac/textleft.png \
		images/mac/textbold.png \
		images/mac/editpaste.png \
		images/mac/zoomin.png \
		images/mac/textjustify.png \
		images/win/editredo.png \
		images/win/exportpdf.png \
		images/win/textright.png \
		images/win/fileprint.png \
		images/win/editcopy.png \
		images/win/textunder.png \
		images/win/editundo.png \
		images/win/filesave.png \
		images/win/editcut.png \
		images/win/fileopen.png \
		images/win/textcenter.png \
		images/win/zoomout.png \
		images/win/textitalic.png \
		images/win/filenew.png \
		images/win/textleft.png \
		images/win/textbold.png \
		images/win/editpaste.png \
		images/win/zoomin.png \
		images/win/textjustify.png
	/usr/lib64/qt4/bin/rcc -name textedit textedit.qrc -o qrc_textedit.cpp

compiler_image_collection_make_all: ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

debug/obj/main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/obj/main.o main.cpp

debug/obj/mainwindow.o: mainwindow.cpp mainwindow.h \
		browser.h \
		treemodel.h \
		common.h \
		treeitem.h \
		itemselectionmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/obj/mainwindow.o mainwindow.cpp

debug/obj/customdelegate.o: customdelegate.cpp customdelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/obj/customdelegate.o customdelegate.cpp

debug/obj/browser.o: browser.cpp browser.h \
		treemodel.h \
		common.h \
		treeitem.h \
		itemselectionmodel.h \
		customdelegate.h \
		sqlconnectiondialog.h \
		textedit.h \
		odt/allconfig.h \
		odt/docformat/ooo/document.h \
		odt/docformat/ooo/converter.h \
		odt/docformat/ooo/styleparser.h \
		odt/docformat/ooo/formatproperty.h \
		odt/docformat/ooo/styleinformation.h \
		odt/tools/kzip.h \
		odt/tools/docmargin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/obj/browser.o browser.cpp

debug/obj/sqlconnectiondialog.o: sqlconnectiondialog.cpp sqlconnectiondialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/obj/sqlconnectiondialog.o sqlconnectiondialog.cpp

debug/obj/treeitem.o: treeitem.cpp treeitem.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/obj/treeitem.o treeitem.cpp

debug/obj/treemodel.o: treemodel.cpp treeitem.h \
		common.h \
		treemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/obj/treemodel.o treemodel.cpp

debug/obj/itemselectionmodel.o: itemselectionmodel.cpp itemselectionmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/obj/itemselectionmodel.o itemselectionmodel.cpp

debug/obj/textedit.o: textedit.cpp textedit.h \
		odt/allconfig.h \
		odt/docformat/ooo/document.h \
		odt/docformat/ooo/converter.h \
		odt/docformat/ooo/styleparser.h \
		odt/docformat/ooo/formatproperty.h \
		odt/docformat/ooo/styleinformation.h \
		odt/tools/kzip.h \
		odt/tools/docmargin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/obj/textedit.o textedit.cpp

debug/obj/kzip.o: odt/tools/kzip.cpp odt/tools/kzip.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/obj/kzip.o odt/tools/kzip.cpp

debug/obj/docmargin.o: odt/tools/docmargin.cpp odt/tools/docmargin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/obj/docmargin.o odt/tools/docmargin.cpp

debug/obj/styleparser.o: odt/docformat/ooo/styleparser.cpp odt/docformat/ooo/styleparser.h \
		odt/docformat/ooo/formatproperty.h \
		odt/docformat/ooo/document.h \
		odt/docformat/ooo/styleinformation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/obj/styleparser.o odt/docformat/ooo/styleparser.cpp

debug/obj/styleinformation.o: odt/docformat/ooo/styleinformation.cpp odt/docformat/ooo/styleinformation.h \
		odt/docformat/ooo/formatproperty.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/obj/styleinformation.o odt/docformat/ooo/styleinformation.cpp

debug/obj/formatproperty.o: odt/docformat/ooo/formatproperty.cpp odt/docformat/ooo/formatproperty.h \
		odt/docformat/ooo/styleinformation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/obj/formatproperty.o odt/docformat/ooo/formatproperty.cpp

debug/obj/document.o: odt/docformat/ooo/document.cpp odt/docformat/ooo/document.h \
		odt/tools/kzip.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/obj/document.o odt/docformat/ooo/document.cpp

debug/obj/converter.o: odt/docformat/ooo/converter.cpp odt/docformat/ooo/document.h \
		odt/docformat/ooo/styleinformation.h \
		odt/docformat/ooo/formatproperty.h \
		odt/docformat/ooo/converter.h \
		odt/docformat/ooo/styleparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/obj/converter.o odt/docformat/ooo/converter.cpp

debug/obj/moc_mainwindow.o: moc/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/obj/moc_mainwindow.o moc/moc_mainwindow.cpp

debug/obj/moc_customdelegate.o: moc/moc_customdelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/obj/moc_customdelegate.o moc/moc_customdelegate.cpp

debug/obj/moc_browser.o: moc/moc_browser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/obj/moc_browser.o moc/moc_browser.cpp

debug/obj/moc_sqlconnectiondialog.o: moc/moc_sqlconnectiondialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/obj/moc_sqlconnectiondialog.o moc/moc_sqlconnectiondialog.cpp

debug/obj/moc_treemodel.o: moc/moc_treemodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/obj/moc_treemodel.o moc/moc_treemodel.cpp

debug/obj/moc_itemselectionmodel.o: moc/moc_itemselectionmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/obj/moc_itemselectionmodel.o moc/moc_itemselectionmodel.cpp

debug/obj/moc_textedit.o: moc/moc_textedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/obj/moc_textedit.o moc/moc_textedit.cpp

debug/obj/moc_docmargin.o: moc/moc_docmargin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/obj/moc_docmargin.o moc/moc_docmargin.cpp

debug/obj/qrc_textedit.o: qrc_textedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/obj/qrc_textedit.o qrc_textedit.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

